log_level: 'DEBUG'

session:
  secret: 'default session secret ...'

ext:
  userprofile:
    url: 'http://profile.example.com'
    access_token: 'secret'
  auth_service:
    url: 'http://auth.example.com'
  batch_reporting:
    url: 'http://reporting.example.com'
    internal_api_version: 'v1'

feature:
  change_role:
    enabled: false
  deactivate_account:
    enabled: false
  logout_user:
    enabled: false
